### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by CG-Spectre** [CG-Spectre/frcslam#2]
### TODO List

- [ ] Pi read from camera
- [ ] Pi read from LiDAR
- [ ] Depth detection
- [ ] modeling on the fly
